class Halo:
    def __init__(self, text: str = "", interval: int = -1) -> None: ...
    def start(self) -> None: ...
    def stop_and_persist(self, symbol: str, text: str = "") -> None: ...
    _spinner: dict[str, list[str]]
